---
# Source: servicemesh-istio-resource/templates/istio-controlplane.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane-1-11-7
  namespace: 
spec:
  hub: gcr.io/istio-testing
  tag: 1.11-alpha.aa439f6e4772aa52acafa11ac7a5fbdfbb160357
  revision: 1-11-7
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    enablePrometheusMerge: true
    enableAutoMtls: false
    extensionProviders:
    - name: jaeger-collector
      envoyExtAuthzGrpc:
        service: jaeger-operator-jaeger-collector.istio-system.svc
        port: 14250
    defaultConfig:
      discoveryAddress: istiod-1-11-7.istio-system.svc:15012
      tracing:
        zipkin:
          address: jaeger-operator-jaeger-collector.istio-system.svc:9411
        sampling: 100
  values:
    global:
      logging:
        level: "default:info"
      istioNamespace: istio-system
  components:
    pilot:
      k8s:
        env:
        - name: PILOT_TRACE_SAMPLING
          value: "100"
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
        hpaSpec:
          maxReplicas: 10
          minReplicas: 1
        nodeSelector:
          servicemesh: enabled
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
    egressGateways:
    - name: istio-egressgateway
      enabled: false

