# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: lma
  labels:
    helm.sh/chart: grafana-5.5.7
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "7.1.1"
    app.kubernetes.io/managed-by: Helm
data:
  plugins: vonage-status-panel,grafana-piechart-panel,devopsprodigy-kubegraf-app
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth]
    disable_login_form = false
    oauth_auto_login = true
    signout_redirect_url = http://localhost:8080/api/v1/sso/logout?path=http://localhost:4200
    [auth.generic_oauth]
    allow_sign_up = true
    api_url = https://keycloak-ahnsk.taco-cat.xyz/auth/realms/hanu-reference/protocol/openid-connect/userinfo
    auth_url = https://keycloak-ahnsk.taco-cat.xyz/auth/realms/hanu-reference/protocol/openid-connect/auth
    client_id = grafana
    client_secret = e0512292-7d00-43df-9d5a-f73ca5684f52
    enabled = true
    name = keycloakOAuth
    scopes = openid profile email
    token_url = https://keycloak-ahnsk.taco-cat.xyz/auth/realms/hanu-reference/protocol/openid-connect/token
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [plugins]
    devopsprodigy-kubegraf-app = true
    grafana-piechart-panel = true
    vonage-status-panel = true
    [security]
    allow_embedding = true
    cookie_samesite = none
    cookie_secure = true
    [server]
    domain = dashboard-ahnsk.taco-cat.xyz
    root_url = https://dashboard-ahnsk.taco-cat.xyz/grafana
    serve_from_sub_path = true
    [users]
    auto_assign_org = true
    auto_assign_org_role = Admin
